using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using ThuongMaiDienTu.Data;
using ThuongMaiDienTu.ViewModels;
namespace ThuongMaiDienTu.Services;
public interface IChatAssistantService { Task<ChatAssistantResponse> ReplyAsync(ChatAssistantRequest request, ClaimsPrincipal user, CancellationToken cancellationToken); }
public sealed class LocalChatAssistantService(ThuongMaiDienTuDbContext context) : IChatAssistantService
{
 public async Task<ChatAssistantResponse> ReplyAsync(ChatAssistantRequest request, ClaimsPrincipal user, CancellationToken token) { var m=request.Message.Trim(); var n=m.ToLowerInvariant(); if(n.Contains("xin chào")||n.Contains("hello")||n=="chào") return new("Xin chào! Tôi có thể tìm sản phẩm, gian hàng, danh mục hoặc hướng dẫn đặt hàng.","greeting",[],[],[],null,["Tìm bàn làm việc","Cách đặt hàng"]); var intent=n.Contains("đơn")||n.Contains("order")?"order_lookup":n.Contains("gian hàng")||n.Contains("store")?"store_search":n.Contains("danh mục")||n.Contains("category")?"category_search":n.Contains("đặt hàng")||n.Contains("checkout")?"checkout_help":n.Contains("vận chuyển")?"shipping_help":n.Contains("đánh giá")||n.Contains("review")?"review_help":"product_search"; if(intent=="order_lookup") return await Order(user,token); if(intent=="store_search") { var s=await context.Stores.AsNoTracking().Where(x=>x.Status=="ACTIVE"&&x.StoreName.Contains(m)).Take(5).Select(x=>new ChatStoreSuggestion(x.StoreName,x.Slug,"/cua-hang/"+x.Slug)).ToListAsync(token); return new("Đây là các gian hàng phù hợp.",intent,[],s,[],null,[]); } if(intent=="category_search") { var c=await context.ProductCategories.AsNoTracking().Where(x=>x.Status=="ACTIVE"&&x.CategoryName.Contains(m)).Take(5).Select(x=>new ChatCategorySuggestion(x.CategoryName,x.Slug,"/danh-muc/"+x.Slug)).ToListAsync(token); return new("Đây là các danh mục phù hợp.",intent,[],[],c,null,[]); } if(intent=="checkout_help") return new("Chọn SKU, thêm vào giỏ rồi thực hiện checkout.",intent,[],[],[],null,[]); if(intent=="shipping_help") return new("Thông tin vận chuyển nằm trong đơn hàng.",intent,[],[],[],null,[]); if(intent=="review_help") return new("Bạn có thể đánh giá sau khi đơn đủ điều kiện.",intent,[],[],[],null,[]); var now=DateTime.Now; var rows=await context.Products.AsNoTracking().Where(x=>x.Status=="ACTIVE"&&x.Store.Status=="ACTIVE"&&x.Category.Status=="ACTIVE"&&x.ProductSkus.Any(s=>s.Status=="ACTIVE")&&(x.ProductName.Contains(m)||x.Store.StoreName.Contains(m)||x.Category.CategoryName.Contains(m))).Select(x=>new{x.ProductName,x.Slug,StoreName=x.Store.StoreName,StoreSlug=x.Store.Slug,CategoryName=x.Category.CategoryName,CategorySlug=x.Category.Slug,Sku=x.ProductSkus.Where(s=>s.Status=="ACTIVE").OrderBy(s=>s.SkuId).Select(s=>new{s.Price,s.SalePrice,s.SaleStart,s.SaleEnd,s.StockQuantity}).First()}).Take(5).ToListAsync(token); var p=rows.Select(x=>{var z=ProductPricingHelper.Calculate(x.Sku.Price,x.Sku.SalePrice,x.Sku.SaleStart,x.Sku.SaleEnd,now);return new ChatProductSuggestion(x.ProductName,x.Slug,z.CurrentPrice,z.IsOnSale?x.Sku.Price:null,x.StoreName,x.StoreSlug,x.CategoryName,x.CategorySlug,x.Sku.StockQuantity>0,"/san-pham/"+x.Slug);}).ToList(); return new(p.Count==0?"Không tìm thấy sản phẩm công khai phù hợp.":"Tôi tìm thấy sản phẩm phù hợp.","product_search",p,[],[],null,[]); }
 private async Task<ChatAssistantResponse> Order(ClaimsPrincipal user,CancellationToken token){if(!long.TryParse(user.FindFirstValue(ClaimTypes.NameIdentifier),out var id))return new("Bạn cần đăng nhập để tra cứu đơn hàng.","order_lookup",[],[],[],null,["Đăng nhập"]);var o=await context.Orders.AsNoTracking().Where(x=>x.UserId==id).OrderByDescending(x=>x.CreatedAt).Select(x=>new ChatOrderSummary(x.OrderCode,x.CreatedAt,x.OrderStatus,x.TotalAmount)).FirstOrDefaultAsync(token);return new(o is null?"Không tìm thấy hoặc không có quyền truy cập đơn hàng.":$"Đơn gần nhất: {o.OrderCode}, trạng thái {o.Status}, tổng {o.Total:N0} đ.","order_lookup",[],[],[],o,[]);}
}
